debug: true
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:basketclub
    username: sa
    password: password