/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basketclub;

import org.junit.jupiter.api.Test;

class BasketClubApplicationTest {
    @Test
    void appHasAGreeting() {
        BasketClubApplication classUnderTest = new BasketClubApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
